#ifndef combine_h
#define combine_h

#include "TestProposal.h"
#include "DebugProposal.h"
#include "VerticalInterpPdf.h"
#include "VerticalInterpHistPdf.h"
#include "AsymPow.h"
#include "CombDataSetFactory.h"
#include "TH1Keys.h"
#include "RooSimultaneousOpt.h"
#include "SimpleCacheSentry.h"
#include "th1fmorph.h"
#include "HZZ4L_RooCTauPdf_1D.h"
#include "HZZ4L_RooCTauPdf_1D_Expanded.h"
#include "HZZ4L_RooCTauPdf_2D.h"
#include "HZZ4LRooPdfs.h"
#include "HWWLVJRooPdfs.h"
#include "HZZ2L2QRooPdfs.h"
#include "HZGRooPdfs.h"
#include "SequentialMinimizer.h"
#include "ProcessNormalization.h"
#include "RooSpline1D.h"
#include "RooSplineND.h"
#include "RooScaleLOSM.h"
#include "RooMultiPdf.h"
#include "RooBernsteinFast.h"
#include "SimpleGaussianConstraint.h"
#include "SimplePoissonConstraint.h"
#include "SimpleConstraintGroup.h"
#include "AtlasPdfs.h"
#include "FastTemplateFunc.h"
#include "HZZ4L_RooSpinZeroPdf.h"
#include "HZZ4L_RooSpinZeroPdf_1D.h"
#include "HZZ4L_RooSpinZeroPdf_2D.h"
#include "HZZ4L_RooSpinZeroPdf_phase.h"
#include "VBFHZZ4L_RooSpinZeroPdf.h"
#include "VBFHZZ4L_RooSpinZeroPdf_fast.h"

#include "HZZ4L_RooSpinZeroPdf_1D_fast.h"
#include "HZZ4L_RooSpinZeroPdf_2D_fast.h"
#include "HZZ4L_RooSpinZeroPdf_phase_fast.h"
#include "VVHZZ4L_RooSpinZeroPdf_1D_fast.h"

#include "HWWLVJJRooPdfs.h"
#include "RooMorphingPdf.h"
#include "RooParametricHist.h"
#include "RooParametricHist2D.h"
#include "RooParametricShapeBinPdf.h"
#include "GaussExp.h"
#include "RooDoubleCBFast.h"
#include "CMSHistFunc.h"
#include "CMSHistErrorPropagator.h"
#include "CMSHistSum.h"
#include "CMSHistFuncWrapper.h"
#include "RooTaylorExpansion.h"
#include "SimpleTaylorExpansion1D.h"


#include "RooCheapProduct.h"
#include "CMSHggFormula.h"
#include "SimpleProdPdf.h"
#include "CMSExternalMorph.h"
#include "CMSInterferenceFunc.h"
#include "RooEFTScalingFunction.h"

#endif
